name: Build and Sign Release APK

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Android
        uses: android-actions/setup-android@v2
        with:
          android-api-level: '29'
          android-build-tools: '29.0.3'
          android-sdk: '29'

      - name: Build release APK
        run: |
          ./gradlew assembleRelease

      - name: Sign release APK
        uses: stebeg/sign-android-apk@v1
        with:
          signing-key-base64: ${{ secrets.SIGNING_KEY_BASE64 }}
          signing-key-password: ${{ secrets.SIGNING_KEY_PASSWORD }}
          signing-key-alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          apk-file-path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload signed APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
