name: Build Unsigned APK

on:
  push:
    branches:
      - master # Or your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Or your desired Java version

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build unsigned APK
        run: ./gradlew assembleDebug

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v3
        with:
          name: unsigned-apk
          path: app/build/outputs/apk/debug/app-debug.apk
